version: "3.9"

services:
  aaibot-rag:
    build: .
    container_name: aaibot-rag
    ports:
      - "8000:8000"
    volumes:
      - ./VectorDB:/app/VectorDB
    environment:
      - OLLAMA_HOST=http://localhost:11434
